version: "3.4"

services:
  main:
    init: true
    image: node:16.14.2-alpine
    command: ['npm', 'run', 'start:dev']
    networks:
      - blog_net
    ports:
      - 3108:3108
    restart: always
    working_dir: /usr/app
    volumes:
      - .:/usr/app
    environment:
      NODE_ENV: development
      APP__HTTP_PORT: 3108
      APP__HTTP_TIMEOUT: 10000
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "1"
  
  postgres-blog-db:
    image: postgres:15.1
    environment:
      POSTGRES_DB: "blog"
      POSTGRES_USER: "bloguser"
      POSTGRES_PASSWORD: "qwebloguser"
    restart: always
    ports:
      - "5435:5432"
    networks:
      - blog_net
    
networks:
  blog_net:
    driver: bridge
    name: blog_net